library(shiny)
library(data.table)
library(dtplyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(DT)
library(ggseqlogo)
library(shinyWidgets)
library(plotly)
library(shinyBS)
library(shinyjs)
library(svglite)
source("./modules/minMaxSlider.R")
source("./modules/reactiveUIOutputModules.R")
source("./modules/downloadFigure.R")
#m <- data.table(m)